### ISSUE TITLE
What's the license for this repo?

### ISSUE THREAD

**Issue by mykaul** [ianmiell/shutit-openshift-cluster#2]

**Comment by ianmiell** [comment]
MIT. I'll update. Didn't think anyone would be interested! Do you have a use for it?

**Comment by mykaul** [comment]
I was looking for OCP deployment using Ansible and Vagrant and Google find this.
I do NOT have a use case for it, as I believe we should not invent yet another OCP deployer.
But I would not look at it without an open license ;-)

**Comment by ianmiell** [comment]
We were forced to use Chef at $WORK (and others were in the same situation).
Also, the ansible solution has proved too slow for many users. I believe
RedHat are ditching Ansible for 'Operators' soon.
